include mk/var.mk
include mk/version.mk
include mk/dirs.mk
include mk/cross.mk
BINAME = $(MODULE)_$(HW)_$(BRANCH)_$(REL)_$(NOW)
include mk/tool.mk
include mk/src.mk
include mk/cmake.mk
include mk/package.mk
include mk/cfg.mk
include mk/all.mk
include mk/format.mk
include mk/rule.mk
include mk/debug.mk
include mk/doc.mk
include mk/ref.mk
include mk/install.mk
include mk/merge.mk
include mk/rust.mk
