# https://youtu.be/TOAynddiu5M?si=bECN6n9yf5ZRuO2y&t=692

[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
rustflags = ["-C","link-arg=-Tlink.x"]
# runner = 'probe-rs run --chip STM32F407VGTx'
# runner = "qemu-system-arm -M -cpu cortex-m3 -machine lm3s6965evb -nographic -semihosting-config enable=on,target=native -kernel"
runner = "qemu-system-arm -M netduinoplus2 -cpu cortex-m4 -nographic -S -s -kernel"
