STM32F407VGTx_FLASH.ld.orig: STM32F407VGTx_FLASH.ld
	dos2unix $< *.patch ; cp $< $@
	patch $< 0001-STM32F407VGTx_FLASH.ld.patch
	patch $< 0002-STM32F407VGTx_FLASH.ld.patch
	patch $< 0003-STM32F407VGTx_FLASH.ld.patch
	patch $< 0004-STM32F407VGTx_FLASH.ld.patch
	patch $< 0005-STM32F407VGTx_FLASH.ld.patch
	patch $< 0006-STM32F407VGTx_FLASH.ld.patch
	patch $< 0007-STM32F407VGTx_FLASH.ld.patch
	patch $< 0008-STM32F407VGTx_FLASH.ld.patch
