# https://gist.github.com/weibeld/f136048d0a82aacc063f42e684e3c494

name: hello

on:
  push:
    branches: [ 'dponyatov' ]

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step1
        run: echo "Hello World!"
      - name: my-step2
        run: echo "Hello World again!"
